# Generated by Django 4.2 on 2024-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='attachments')),
            ],
        ),
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(upload_to='mentor_profile_pics')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('book_a_slot', models.BooleanField(default=False)),
                ('attachments', models.ManyToManyField(blank=True, to='mentor.attachment')),
            ],
        ),
        migrations.RemoveField(
            model_name='sessionschedule',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sessionschedule',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='SessionSchedule',
        ),
    ]
